/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_01.forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author troy
 */
public class filling_form extends javax.swing.JFrame {
    private static final String username = "root" ;
    private static final String password = "1234" ;
    private static final String dataconn = "jdbc:mysql://127.0.0.1:3306/employees" ; 
    
     Connection sql = null;
    PreparedStatement pst  = null;
    ResultSet rs = null;
    int q, i;
    /**
     * Creates new form filling_form
     */
    public filling_form() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Firstname = new javax.swing.JTextField();
        Middlename = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        Position = new javax.swing.JTextField();
        Department = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Plantilla = new javax.swing.JTextField();
        employee = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        middlename = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Employee = new javax.swing.JComboBox<>();
        plantilla = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 102, 255));
        kGradientPanel1.setkGradientFocus(10);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register Employee");

        Id.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Id.setPreferredSize(new java.awt.Dimension(64, 17));

        Firstname.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Firstname.setPreferredSize(new java.awt.Dimension(64, 17));

        Middlename.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Middlename.setPreferredSize(new java.awt.Dimension(64, 17));

        Lastname.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Lastname.setPreferredSize(new java.awt.Dimension(64, 17));

        Position.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Position.setPreferredSize(new java.awt.Dimension(64, 17));

        Department.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Department.setPreferredSize(new java.awt.Dimension(64, 17));

        Date.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Date.setPreferredSize(new java.awt.Dimension(64, 17));

        Plantilla.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Plantilla.setPreferredSize(new java.awt.Dimension(64, 17));

        employee.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        employee.setText("Employee Type");

        id.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        id.setText("ID NO.");

        firstname.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        firstname.setText("FIRSTNAME:");

        middlename.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        middlename.setText("MIDDLENAME:");

        lastname.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        lastname.setText("LASTNAME:");

        position.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        position.setText("POSITION/DESIGNATION:");

        department.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        department.setText("DEPARTMENT:");

        date.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        date.setText("DATE ASSUMED TO OFFICE:");

        Employee.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        Employee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senior High School", "Junior High School", "Non-Teaching Personnel" }));
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });

        plantilla.setFont(new java.awt.Font("Lucida Bright", 3, 12)); // NOI18N
        plantilla.setText("PLANTILLA ITEM NUMBER:");

        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel2.setkGradientFocus(10);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CLOSE");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employee)
                            .addComponent(id)
                            .addComponent(firstname)
                            .addComponent(middlename)
                            .addComponent(lastname)
                            .addComponent(position)
                            .addComponent(department)
                            .addComponent(date)
                            .addComponent(plantilla))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Middlename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Plantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register)
                .addGap(231, 231, 231))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(employee)
                        .addGap(43, 43, 43)
                        .addComponent(id)
                        .addGap(33, 33, 33)
                        .addComponent(firstname)
                        .addGap(29, 29, 29)
                        .addComponent(middlename)
                        .addGap(31, 31, 31)
                        .addComponent(lastname)
                        .addGap(31, 31, 31)
                        .addComponent(position)
                        .addGap(30, 30, 30)
                        .addComponent(department)
                        .addGap(38, 38, 38)
                        .addComponent(date)
                        .addGap(31, 31, 31)
                        .addComponent(plantilla))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(Firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Middlename, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Plantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void UpdateDb1() {
     try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String jdbcUrl = "jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC";
        String username = "your_username";
        String password = "your_password";
        
        sql = DriverManager.getConnection(jdbcUrl, username, password);
        pst = sql.prepareStatement("SELECT * FROM jhs_employee");
        rs = pst.executeQuery();
        
        while (rs.next()) {
            int id = rs.getInt("ID_No_jhs");
            String first_name = rs.getString("first_name");
            String midle_name = rs.getString("midle_name");
            String family_name = rs.getString("family_name");
            String position = rs.getString("position");
            String department = rs.getString("department");
            String date = rs.getString("date_assumed");
            String plantilla = rs.getString("item_No");
           
           
        }
    } catch (ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
        e.printStackTrace(); 
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (sql != null) sql.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        admin_page adminpage = new admin_page();
         adminpage.show();
         
         dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection sql = DriverManager.getConnection(dataconn, username, password);
    PreparedStatement pst = sql.prepareStatement("INSERT INTO jhs_employee (first_name, midle_name, last_name, family_name, position,department, date_assumed, item_No) VALUES (?,?,?,?,?,?,?,?) ");
    
    String id = Id.getText();
    String firstname = Firstname.getText();
    String midlename = Middlename.getText();
    String lastname = Lastname.getText();
    String position = Position.getText();
    String department = Department.getText();
    String date = Date.getText();
    String plantilla = Plantilla.getText();
      

    if(Id == null || Firstname == null || Middlename == null || Lastname == null || Position == null || Department == null || Date == null || Plantilla == null) {
       
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
   
    
    pst.executeUpdate();
    JOptionPane.showMessageDialog(this, "Record Added");
    
    Id.setText("");
    Firstname.setText("");
    Middlename.setText("");
    Lastname.setText("");
    Position.setText("");
    Department.setText("");
    Date.setText("");
    Plantilla.setText("");
    Id.requestFocus();
    
    
    
    dispose();
          
} catch (ClassNotFoundException ex) {
    ex.printStackTrace(); 
    JOptionPane.showMessageDialog(this, "Database driver not found", "Error", JOptionPane.ERROR_MESSAGE);
} catch (SQLException ex) {
    ex.printStackTrace(); 
    JOptionPane.showMessageDialog(this, "Error inserting record: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}  
    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(filling_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(filling_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(filling_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(filling_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new filling_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Department;
    private javax.swing.JComboBox<String> Employee;
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Lastname;
    private javax.swing.JTextField Middlename;
    private javax.swing.JTextField Plantilla;
    private javax.swing.JTextField Position;
    private javax.swing.JLabel date;
    private javax.swing.JLabel department;
    private javax.swing.JLabel employee;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel id;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lastname;
    private javax.swing.JLabel middlename;
    private javax.swing.JLabel plantilla;
    private javax.swing.JLabel position;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
